import loadable from '@loadable/component'

export const PathsArray = {
    "א": [{audio: require('../../assets/letterAudio/lion.mp3'), address: require('../../assets/wordsImages/1/Lion.png'), word: 'ריה'}, {audio: require('../../assets/letterAudio/plane.mp3'), address: require('../../assets/wordsImages/1/Plane.png'), word: 'וירון'}, {audio: require('../../assets/letterAudio/rabbit.mp3'), address: require('../../assets/wordsImages/1/Rabbit.png'), word: 'רנב'}],
    "ב": [{audio: require('../../assets/letterAudio/duck.mp3'), address: require('../../assets/wordsImages/2/Duck.png'), word: 'רווז'}, {audio: require('../../assets/letterAudio/onion.mp3'), address: require('../../assets/wordsImages/2/Onion.png'), word: 'צל'}, {audio: require('../../assets/letterAudio/balloon.mp3'), address: require('../../assets/wordsImages/2/Balloon.png'), word: 'לון'}],
    "ג": [{audio: require('../../assets/letterAudio/giraffe.mp3'), address: require('../../assets/wordsImages/3/Giraffe.png'), word: "'ירפה"}, {audio: require('../../assets/letterAudio/fence.mp3'), address: require('../../assets/wordsImages/3/Fence.png'), word: 'דר'}, {audio: require('../../assets/letterAudio/camel.mp3'), address: require('../../assets/wordsImages/3/Camel.png'), word: 'מל'}],
    "ד": [{audio: require('../../assets/letterAudio/Scarecrow.mp3'), address: require('../../assets/wordsImages/4/Scarecrow.png'), word: 'חליל'}, {audio: require('../../assets/letterAudio/bucket.mp3'), address: require('../../assets/wordsImages/4/Bucket.png'), word: 'לי'}, {audio: require('../../assets/letterAudio/dolphin.mp3'), address: require('../../assets/wordsImages/4/Dolphin.png'), word: 'ולפין'}],
    "ה": [{audio: require('../../assets/letterAudio/SteeringWheel.mp3'), address: require('../../assets/wordsImages/5/SteeringWheel.png'), word: 'גה'}, {audio: require('../../assets/letterAudio/mountain.mp3'), address: require('../../assets/wordsImages/5/Mountain.png'), word: 'ר'}, {audio: require('../../assets/letterAudio/Hippopotamus.mp3'), address: require('../../assets/wordsImages/5/Hippopotamus.png'), word: 'יפופוטם'}],
    "ו": [{audio: require('../../assets/letterAudio/hook.mp3'), address: require('../../assets/wordsImages/6/Hook.png'), word: 'ו'}, {audio: require('../../assets/letterAudio/rose.mp3'), address: require('../../assets/wordsImages/6/Rose.png'), word: 'רד'}, {audio: require('../../assets/letterAudio/Curtain.mp3'), address: require('../../assets/wordsImages/6/Curtain.png'), word: 'ילון'}],
    "ז": [{audio: require('../../assets/letterAudio/zebra.mp3'), address: require('../../assets/wordsImages/7/Zebra.png'), word: 'ברה'}, {audio: require('../../assets/letterAudio/singer.mp3'), address: require('../../assets/wordsImages/7/Singer.png'), word: 'מר'}, {audio: require('../../assets/letterAudio/Caterpillar.mp3'), address: require('../../assets/wordsImages/7/Caterpillar.png'), word: 'חל'}],
    "ח": [{audio: require('../../assets/letterAudio/Snail.mp3'), address: require('../../assets/wordsImages/8/Snail.png'), word: 'ילזון'}, {audio: require('../../assets/letterAudio/Sunflower.mp3'), address: require('../../assets/wordsImages/8/Sunflower.png'), word: 'מניה'}, {audio: require('../../assets/letterAudio/Stork.mp3'), address: require('../../assets/wordsImages/8/Stork.png'), word: 'סידה'}],
    "ט": [{audio: require('../../assets/letterAudio/tractor.mp3'), address: require('../../assets/wordsImages/9/Tractor.png'), word: 'רקטור'}, {audio: require('../../assets/letterAudio/Peacock.mp3'), address: require('../../assets/wordsImages/9/Peacock.png'), word: 'ווס'}, {audio: require('../../assets/letterAudio/ring.mp3'), address: require('../../assets/wordsImages/9/Ring.png'), word: 'בעת'}],
    "י": [{audio: require('../../assets/letterAudio/Ostrich.mp3'), address: require('../../assets/wordsImages/10/Ostrich.png'), word: 'ען'}, {audio: require('../../assets/letterAudio/dimond.mp3'), address: require('../../assets/wordsImages/10/Diamond.png'), word: 'הלום'}, {audio: require('../../assets/letterAudio/owl.mp3'), address: require('../../assets/wordsImages/10/Owl.png'), word: 'נשוף'}],
    "כ": [{audio: require('../../assets/letterAudio/sheep.mp3'), address: require('../../assets/wordsImages/11/Sheep.png'), word: 'בשה'}, {audio: require('../../assets/letterAudio/hat.mp3'), address: require('../../assets/wordsImages/11/Hat.png'), word: 'ובע'}, {audio: require('../../assets/letterAudio/ball.mp3'), address: require('../../assets/wordsImages/11/Ball.png'), word: 'דור '}],
    "ל": [{audio: require('../../assets/letterAudio/heart.mp3'), address: require('../../assets/wordsImages/12/Heart.png'), word: 'ב'}, {audio: require('../../assets/letterAudio/lemon.mp3'), address: require('../../assets/wordsImages/12/Lemon.png'), word: 'ימון'}, {audio: require('../../assets/letterAudio/whale.mp3'), address: require('../../assets/wordsImages/12/Whale.png'), word: 'וויתן'}],
    "מ": [{audio: require('../../assets/letterAudio/whistle.mp3'), address: require('../../assets/wordsImages/13/Whistle.png'), word: 'שרוקית'}, {audio: require('../../assets/letterAudio/jellyfish.mp3'), address: require('../../assets/wordsImages/13/Jellyfish.png'), word: 'דוזה'}, {audio: require('../../assets/letterAudio/glasses.mp3'), address: require('../../assets/wordsImages/13/Glasses.png'), word: 'שקפיים'}],
    "נ": [{audio: require('../../assets/letterAudio/eagle.mp3'), address: require('../../assets/wordsImages/14/Eagle.png'), word: 'שר'}, {audio: require('../../assets/letterAudio/Narcissus.mp3'), address: require('../../assets/wordsImages/14/Narcissus.png'), word: 'רקיס'}, {audio: require('../../assets/letterAudio/shoe.mp3'), address: require('../../assets/wordsImages/14/Shoe.png'), word: 'על'}],
    "ס": [{audio: require('../../assets/letterAudio/horse.mp3'), address: require('../../assets/wordsImages/15/Horse.png'), word: 'וס'}, {audio: require('../../assets/letterAudio/boat.mp3'), address: require('../../assets/wordsImages/15/Boat.png'), word: 'ירה'}, {audio: require('../../assets/letterAudio/Squirrel.mp3'), address: require('../../assets/wordsImages/15/Squirrel.png'), word: 'נאי'}],
    "ע": [{audio: require('../../assets/letterAudio/mouse.mp3'), address: require('../../assets/wordsImages/16/Mouse.png'), word: 'כבר'}, {audio: require('../../assets/letterAudio/kite.mp3'), address: require('../../assets/wordsImages/16/Kite.png'), word: 'פיפון'}, {audio: require('../../assets/letterAudio/tomato.mp3'), address: require('../../assets/wordsImages/16/Tomato.png'), word: 'גבניה'}],
    "פ": [{audio: require('../../assets/letterAudio/elephant.mp3'), address: require('../../assets/wordsImages/17/Elephant.png'), word: 'יל'}, {audio: require('../../assets/letterAudio/pepper.mp3'), address: require('../../assets/wordsImages/17/Pepper.png'), word: 'לפל'}, {audio: require('../../assets/letterAudio/butterfly.mp3'), address: require('../../assets/wordsImages/17/Butterfly.png'), word: 'רפר'}],
    "צ": [{audio: require('../../assets/letterAudio/frog.mp3'), address: require('../../assets/wordsImages/18/Frog.png'), word: 'פרדע'}, {audio: require('../../assets/letterAudio/Radish.mp3'), address: require('../../assets/wordsImages/18/Radish.png'), word: 'נון'}, {audio: require('../../assets/letterAudio/turtle.mp3'), address: require('../../assets/wordsImages/18/Turtle.png'), word: 'ב'}],
    "ק": [{audio: require('../../assets/letterAudio/Hedgehog.mp3'), address: require('../../assets/wordsImages/19/Hedgehog.png'), word: 'יפוד'}, {audio: require('../../assets/letterAudio/kettle.mp3'), address: require('../../assets/wordsImages/19/Kettle.png'), word: 'ומקום'}, {audio: require('../../assets/letterAudio/rhino.mp3'), address: require('../../assets/wordsImages/19/Rhino.png'), word: 'רנף'}],
    "ר": [{audio: require('../../assets/letterAudio/traffic-light.mp3'), address: require('../../assets/wordsImages/20/TrafficLight.png'), word: 'מזור'}, {audio: require('../../assets/letterAudio/Pomegranate.mp3'), address: require('../../assets/wordsImages/20/Pomegranate.png'), word: 'ימון'}, {audio: require('../../assets/letterAudio/train.mp3'), address: require('../../assets/wordsImages/20/Train.png'), word: 'כבת'}],
    "ש": [{audio: require('../../assets/letterAudio/clock.mp3'), address: require('../../assets/wordsImages/21/Clock.png'), word: 'עון'}, {audio: require('../../assets/letterAudio/necklace.mp3'), address: require('../../assets/wordsImages/21/Necklace.png'), word: 'רשרת'}, {audio: require('../../assets/letterAudio/sun.mp3'), address: require('../../assets/wordsImages/21/Sun.png'), word: 'מש'}],
    "ת": [{audio: require('../../assets/letterAudio/drum.mp3'), address: require('../../assets/wordsImages/22/Drum.png'), word: 'וף'}, {audio: require('../../assets/letterAudio/alligator.mp3'), address: require('../../assets/wordsImages/22/Crocodile.png'), word: 'נין'}, {audio: require('../../assets/letterAudio/apple.mp3'), address: require('../../assets/wordsImages/22/Apple.png'), word: 'פוח'}],
  }
  