export const assets = [
    require('./assets/splash1.png'),
    require('./assets/splash.png'),
    require('./assets/Screenshot.png'),
    require('./assets/ringtone.mp3'),
    require('./assets/monster.png'),
    require('./assets/icon.png'),
    require('./assets/hey.jpeg'),
    require('./assets/Hello.mp3'),
    require('./assets/gimel.jpeg'),
    require('./assets/favicon.png'),
    require('./assets/bet2.jpeg'),
    require('./assets/bet.jpeg'),
    require('./assets/appIcon.png'),
    require('./assets/entrance/entranceAudio.mp3'),
    require('./assets/entrance/entranceAudio.mp4'),
    require('./assets/entrance/entranceGif.gif'),
    require('./assets/gif/animation.gif'),
    require('./assets/gif/newGif.gif'),
    // ('./assets/icon/google.svg',
    require('./assets/images/NewBackground.png'),
    require('./assets/images/Portrait.png'),
    require('./assets/images/LotsOfGreenBackground.png'),
    require('./assets/images/MainBackground.png'),
    // ('./assets/images/ExclamationMark.svg',
    require('./assets/images/Chocolate.png'),
    // ('./assets/images/monster/lastBubble.svg',
    // ('./assets/images/monster/MainMonster.svg',
    // ('./assets/images/monster/MonsterHand.svg',
    // ('./assets/images/monster/monsterHold.svg',
    require('./assets/images/monster/MonsterMouth.png'),
    // ('./assets/images/monster/Monster.svg',
    // ('./assets/images/monster/MonsterWithoutMouth.svg',
    // ('./assets/images/monster/SadMonster.svg',
    require('./assets/images/monster/אנימציה-גירוד-ראש.gif'),
    require('./assets/images/monster/אנימציה-ידיים.gif'),
    require('./assets/images/monster/אנימצציה-ידיים-קטן.gif'),
    // ('./assets/images/message-sent/Arrow.svg',
    // ('./assets/images/message-sent/MonsterOnEnvelope.svg',
    // ('./assets/images/logo/Logo1.svg',
    // ('./assets/images/logo/Logo.svg',
    // ('./assets/images/letters/blueLetter.svg',
    // ('./assets/images/letters/greenLetter.svg',
    require('./assets/images/letters/RandomLetter.png'),
    // ('./assets/images/iconMan/Iconman.svg',
    // ('./assets/images/gallery/Check.svg',
    // ('./assets/images/gallery/Gallery.svg',
    // ('./assets/images/gallery/HomeSign.svg',
    // ('./assets/images/gallery/NewCheck.svg',
    // ('./assets/images/gallery/NewHomeButton.svg',
    // ('./assets/images/gallery/NewRedSign.svg',
    // ('./assets/images/gallery/Pending.svg',
    // ('./assets/images/gallery/Plus.svg',
    // ('./assets/images/gallery/RedSign.svg',
    // ('./assets/images/envelope/envelope.svg',
    // ('./assets/images/entrance/LittleMonster.svg',
    // ('./assets/images/confirm-image/BlueEnvelopeIcon.svg',
    // ('./assets/images/confirm-image/LittleMonster.svg',
    require('./assets/images/confirm-image/newLittleMonster.png'),
    // ('./assets/images/confirm-image/SendImage.svg',
    // ('./assets/images/confirm-image/TryAgain.svg',
    // ('./assets/images/circle/BigTwinkle.svg',
    // ('./assets/images/circle/BlueStart.svg',
    // ('./assets/images/circle/Blue.svg',
    // ('./assets/images/circle/borderAndTwinkles.svg',
    // ('./assets/images/circle/Green.svg',
    // ('./assets/images/circle/LittleTwinkle.svg',
    // ('./assets/images/circle/Orange.svg',
    // ('./assets/images/circle/SmallBlue.svg',
    // ('./assets/images/circle/SmallOrange.svg',
    // ('./assets/images/circle/StarBlue.svg',
    // ('./assets/images/circle/StarGreen.svg',
    // ('./assets/images/circle/StarOrange.svg',
    // ('./assets/images/circle/StarYellow.svg',
    // ('./assets/images/circle/Yellow.svg',
    // ('./assets/images/camera/pressToCamera.svg',
    require('./assets/letterAudio/alligator.mp3'),
    require('./assets/letterAudio/apple.mp3'),
    require('./assets/letterAudio/ball.mp3'),
    require('./assets/letterAudio/balloon.mp3'),
    require('./assets/letterAudio/boat.mp3'),
    require('./assets/letterAudio/bucket.mp3'),
    require('./assets/letterAudio/butterfly.mp3'),
    require('./assets/letterAudio/camel.mp3'),
    require('./assets/letterAudio/cameraSound1.mp3'),
    require('./assets/letterAudio/cameraSound.mp3'),
    require('./assets/letterAudio/Caterpillar.mp3'),
    require('./assets/letterAudio/clock.mp3'),
    require('./assets/letterAudio/Curtain.mp3'),
    require('./assets/letterAudio/dimond.mp3'),
    require('./assets/letterAudio/dolphin.mp3'),
    require('./assets/letterAudio/drum.mp3'),
    require('./assets/letterAudio/duck.mp3'),
    require('./assets/letterAudio/eagle.mp3'),
    require('./assets/letterAudio/elephant.mp3'),
    require('./assets/letterAudio/fence.mp3'),
    require('./assets/letterAudio/first-audio.mp3'),
    require('./assets/letterAudio/frog.mp3'),
    require('./assets/letterAudio/gifAudio(10).mp3'),
    require('./assets/letterAudio/gifAudio(11).mp3'),
    require('./assets/letterAudio/gifAudio(12).mp3'),
    require('./assets/letterAudio/gifAudio(13).mp3'),
    require('./assets/letterAudio/gifAudio(14).mp3'),
    require('./assets/letterAudio/gifAudio(15).mp3'),
    require('./assets/letterAudio/gifAudio(16).mp3'),
    require('./assets/letterAudio/gifAudio(17).mp3'),
    require('./assets/letterAudio/gifAudio(18).mp3'),
    require('./assets/letterAudio/gifAudio(19).mp3'),
    require('./assets/letterAudio/gifAudio(1).mp3'),
    require('./assets/letterAudio/gifAudio(20).mp3'),
    require('./assets/letterAudio/gifAudio(21).mp3'),
    require('./assets/letterAudio/gifAudio(2).mp3'),
    require('./assets/letterAudio/gifAudio(3).mp3'),
    require('./assets/letterAudio/gifAudio(4).mp3'),
    require('./assets/letterAudio/gifAudio(5).mp3'),
    require('./assets/letterAudio/gifAudio(6).mp3'),
    require('./assets/letterAudio/gifAudio(7).mp3'),
    require('./assets/letterAudio/gifAudio(8).mp3'),
    require('./assets/letterAudio/gifAudio(9).mp3'),
    require('./assets/letterAudio/gifAudio.mp3'),
    require('./assets/letterAudio/giraffe.mp3'),
    require('./assets/letterAudio/glasses.mp3'),
    require('./assets/letterAudio/hat.mp3'),
    require('./assets/letterAudio/heart.mp3'),
    require('./assets/letterAudio/Hedgehog.mp3'),
    require('./assets/letterAudio/Hippopotamus.mp3'),
    require('./assets/letterAudio/hook.mp3'),
    require('./assets/letterAudio/horse.mp3'),
    require('./assets/letterAudio/jellyfish.mp3'),
    require('./assets/letterAudio/kettle.mp3'),
    require('./assets/letterAudio/kite.mp3'),
    require('./assets/letterAudio/lemon.mp3'),
    require('./assets/letterAudio/lion.mp3'),
    require('./assets/letterAudio/message-received-audio.mp3'),
    require('./assets/letterAudio/MessageReceived.mp3'),
    require('./assets/letterAudio/messageSent.mp3'),
    require('./assets/letterAudio/mountain.mp3'),
    require('./assets/letterAudio/mouse.mp3'),
    require('./assets/letterAudio/Narcissus.mp3'),
    require('./assets/letterAudio/necklace.mp3'),
    require('./assets/letterAudio/onion.mp3'),
    require('./assets/letterAudio/oops-problem.mp3'),
    require('./assets/letterAudio/Ostrich.mp3'),
    require('./assets/letterAudio/owl.mp3'),
    require('./assets/letterAudio/Peacock.mp3'),
    require('./assets/letterAudio/pepper.mp3'),
    require('./assets/letterAudio/plane.mp3'),
    require('./assets/letterAudio/Pomegranate.mp3'),
    require('./assets/letterAudio/rabbit.mp3'),
    require('./assets/letterAudio/Radish.mp3'),
    require('./assets/letterAudio/rhino.mp3'),
    require('./assets/letterAudio/ring.mp3'),
    require('./assets/letterAudio/rose.mp3'),
    require('./assets/letterAudio/Scarecrow.mp3'),
    require('./assets/letterAudio/sendAgain.mp3'),
    require('./assets/letterAudio/sending-audio.mp3'),
    require('./assets/letterAudio/sheep.mp3'),
    require('./assets/letterAudio/shoe.mp3'),
    require('./assets/letterAudio/shortBeep.mp3'),
    require('./assets/letterAudio/singer.mp3'),
    require('./assets/letterAudio/Snail.mp3'),
    require('./assets/letterAudio/Squirrel.mp3'),
    require('./assets/letterAudio/SteeringWheel.mp3'),
    require('./assets/letterAudio/Stork.mp3'),
    require('./assets/letterAudio/Sunflower.mp3'),
    require('./assets/letterAudio/sun.mp3'),
    require('./assets/letterAudio/take-picture-again-audio.mp3'),
    require('./assets/letterAudio/tomato.mp3'),
    require('./assets/letterAudio/tractor.mp3'),
    require('./assets/letterAudio/traffic-light.mp3'),
    require('./assets/letterAudio/train.mp3'),
    require('./assets/letterAudio/try-again-audio.mp3'),
    require('./assets/letterAudio/turtle.mp3'),
    require('./assets/letterAudio/well-done2.mp3'),
    require('./assets/letterAudio/whale.mp3'),
    require('./assets/letterAudio/whistle.mp3'),
    require('./assets/letterAudio/wiii-audio.mp3'),
    require('./assets/letterAudio/zebra.mp3'),
    require('./assets/letterGifs/letterא.gif'),
    require('./assets/letterGifs/letterב.gif'),
    require('./assets/letterGifs/letterג.gif'),
    require('./assets/letterGifs/letterד.gif'),
    require('./assets/letterGifs/letterה.gif'),
    require('./assets/letterGifs/letterו.gif'),
    require('./assets/letterGifs/letterז.gif'),
    require('./assets/letterGifs/letterח.gif'),
    require('./assets/letterGifs/letterט.gif'),
    require('./assets/letterGifs/letterי.gif'),
    require('./assets/letterGifs/letterכ.gif'),
    require('./assets/letterGifs/letterל.gif'),
    require('./assets/letterGifs/letterמ.gif'),
    require('./assets/letterGifs/letterנ.gif'),
    require('./assets/letterGifs/letterס.gif'),
    require('./assets/letterGifs/letterע.gif'),
    require('./assets/letterGifs/letterפ.gif'),
    require('./assets/letterGifs/letterצ.gif'),
    require('./assets/letterGifs/letterק.gif'),
    require('./assets/letterGifs/letterר.gif'),
    require('./assets/letterGifs/letterש.gif'),
    require('./assets/letterGifs/letterת.gif'),
    // ('./assets/wordsImages/1/Lion1.svg',
    require('./assets/wordsImages/1/Lion.png'),
    require('./assets/wordsImages/1/Plane.png'),
    require('./assets/wordsImages/1/Rabbit.png'),
    require('./assets/wordsImages/2/Balloon.png'),
    require('./assets/wordsImages/2/Duck.png'),
    require('./assets/wordsImages/2/Onion.png'),
    require('./assets/wordsImages/3/Camel.png'),
    require('./assets/wordsImages/3/Fence.png'),
    require('./assets/wordsImages/3/Giraffe.png'),
    require('./assets/wordsImages/4/Bucket.png'),
    require('./assets/wordsImages/4/Dolphin.png'),
    require('./assets/wordsImages/4/Scarecrow.png'),
    require('./assets/wordsImages/5/Hippopotamus.png'),
    require('./assets/wordsImages/5/Mountain.png'),
    require('./assets/wordsImages/5/SteeringWheel.png'),
    require('./assets/wordsImages/6/Curtain.png'),
    require('./assets/wordsImages/6/Hook.png'),
    require('./assets/wordsImages/6/Rose.png'),
    require('./assets/wordsImages/7/Caterpillar.png'),
    require('./assets/wordsImages/7/Singer.png'),
    require('./assets/wordsImages/7/Zebra.png'),
    require('./assets/wordsImages/8/Snail.png'),
    require('./assets/wordsImages/8/Stork.png'),
    require('./assets/wordsImages/8/Sunflower.png'),
    require('./assets/wordsImages/9/Peacock.png'),
    require('./assets/wordsImages/9/Ring.png'),
    require('./assets/wordsImages/9/Tractor.png'),
    require('./assets/wordsImages/10/Diamond.png'),
    require('./assets/wordsImages/10/Ostrich.png'),
    require('./assets/wordsImages/10/Owl.png'),
    require('./assets/wordsImages/11/Ball.png'),
    require('./assets/wordsImages/11/Hat.png'),
    require('./assets/wordsImages/11/Sheep.png'),
    require('./assets/wordsImages/12/Heart.png'),
    require('./assets/wordsImages/12/Lemon.png'),
    require('./assets/wordsImages/12/Whale.png'),
    require('./assets/wordsImages/13/Glasses.png'),
    require('./assets/wordsImages/13/Jellyfish.png'),
    require('./assets/wordsImages/13/Whistle.png'),
    require('./assets/wordsImages/14/Eagle.png'),
    require('./assets/wordsImages/14/Narcissus.png'),
    require('./assets/wordsImages/14/Shoe.png'),
    require('./assets/wordsImages/15/Boat.png'),
    require('./assets/wordsImages/15/Horse.png'),
    require('./assets/wordsImages/15/Squirrel.png'),
    require('./assets/wordsImages/16/Kite.png'),
    require('./assets/wordsImages/16/Mouse.png'),
    require('./assets/wordsImages/16/Tomato.png'),
    require('./assets/wordsImages/17/Butterfly.png'),
    require('./assets/wordsImages/17/Elephant.png'),
    require('./assets/wordsImages/17/Pepper.png'),
    require('./assets/wordsImages/18/Frog.png'),
    require('./assets/wordsImages/18/Radish.png'),
    require('./assets/wordsImages/18/Turtle.png'),
    require('./assets/wordsImages/19/Hedgehog.png'),
    require('./assets/wordsImages/19/Kettle.png'),
    require('./assets/wordsImages/19/Rhino.png'),
    require('./assets/wordsImages/20/Pomegranate.png'),
    require('./assets/wordsImages/20/TrafficLight.png'),
    require('./assets/wordsImages/20/Train.png'),
    require('./assets/wordsImages/21/Clock.png'),
    require('./assets/wordsImages/21/Necklace.png'),
    require('./assets/wordsImages/21/Sun.png'),
    require('./assets/wordsImages/22/Apple.png'),
    require('./assets/wordsImages/22/Crocodile.png'),
    require('./assets/wordsImages/22/Drum.png'),
]